### ISSUE TITLE
P2

### ISSUE THREAD

**Issue by pujiaxun** [Maliaoya/web_tasks#1]
源码就是用git来管理的。你打包成了zip，还如何追踪变更呢？
GitHub不是百度云，主要用来放源代码，而不是可执行文件

**Comment by Maliaoya** [comment]
不好意思，文件太多，习惯性打包，下次不会了
学长代码方面还有其他的问题吗？

**Comment by Maliaoya** [comment]
我已经重新上传好了

**Comment by pujiaxun** [comment]
代码还可以，不过我有些好奇，你是参考的哪个教程？方便给我个链接吗？

**Comment by Maliaoya** [comment]
http://www.imooc.com/learn/563
学长我能问一下为什么我的第一次代码有什么问题吗

**Comment by Maliaoya** [comment]
http://www.imooc.com/learn/563
学长 我能问一下我第一次代码有什么问题吗

**Comment by pujiaxun** [comment]
手动实现了一个加法，但有一个地方写的不是很semantic或者说self document，
`if( result[i]>57 )  //当有进位时，进位+1 ` 这里的57应该就是传说中的magic number了…… 并没有看懂是什么意思。

不过算是溢出问题解决的很不错的了，赞～
